[profile.default]
src = 'src/contracts'
script = 'src/script'
out = 'artifacts'
test = 'src/test'
cache_path = 'forge-cache'
libs = ["node_modules", "lib"]

solc_version = "0.8.10"
extra_output_files = ["metadata"]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/tree/master/config